version: "3"
services:
  node1:
    build:
      dockerfile: Dockerfile 
    environment:
      - NODE_ID=1
    networks:
      - raft_network
    ports:
      - "5001:5000"

  node2:
    build:
      dockerfile: Dockerfile
    environment:
      - NODE_ID=2
    networks:
      - raft_network
    ports:
      - "5002:5000"

  node3:
    build: 
      dockerfile: Dockerfile
    environment:
      - NODE_ID=3
    networks:
      - raft_network
    ports:
      - "5003:5000"


networks:
  raft_network:
    driver: bridge
